# -*- org -*-
#note: !Goken9cc is the futur though so prioritize goken over kencc when possible!

* Last

*** fix segfault with rc in kencc
still useful goal? anyway, want to move to goken no?
update: goken might be further away to compile principia so let's not
 abandon completely kencc

we need a working mk/rc to compile principia, and can use MKSHELL
and 9base to use plan9port rc, but a but annoying
=> better to fix rc in kencc
OR better to port mk/rc from principia to goken?

use gdb
recompile with -O0 and -fno-inline if needed

*** RELAX shell.nix and nix.yml

* Infra

** Build infra

*** port kencc to amd64? or switch to goken?
9cc-colombier did but I had to revert it because I failed to compile it on my
Linux. Still, probably need to port all the uintptr and va_list fixes!

note that goken is working on amd64 (actually it currently only builds on amd64)

*** try to compile kencc from macbook black arm64
should work no? we just use gcc/clang or 64 bit issue?
maybe first port kencc to amd64

*** still? run compiled kencc on kencc/ source? works?
better to get boostrapping on goken

* Old todos

** less: figure out why cant use union with dbuf,
why was not working? print & of dbuf and obuf?
and why was working if you do a print before ...
really weird, probably bug gcc!

*** try clang under Linux? bug with dbuf too?

*** related to tordvalds recent rant about gcc and union and the C standard?
