#                                              -*-makefile-*-
<../mkconfig

LIB=libmach.a
OFILES=\
	6.$O\
	8.$O\
	v.$O\
	8db.$O\
	vdb.$O\
	6obj.$O\
	8obj.$O\
	obj.$O\
	map.$O\
	swap.$O\
	sym.$O\
	access.$O\
	machdata.$O\
	setmach.$O\
	executable.$O\
	vcodas.$O

HFILES=\
	$ROOT/include/mach.h\
	$ROOT/include/a.out.h\
	bootexec.h\
	elf.h\
	ureg2.h\
	ureg4.h\
	ureg6.h\
	ureg8.h\
	uregk.h\
	uregv.h\
	ureg5.h

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
CFLAGS= $CFLAGS -I../cmd/
