#                                              -*-makefile-*-
<../../mkconfig

TARG=sed

OFILES=\
	sed.$O\

LIBS=bio regexp 9		# order is important.

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE

