#!/bin/sh
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 convD2M.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 convM2D.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 convM2S.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 convS2M.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 fcallfmt.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 qsort.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 runestrlen.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 strtoll.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 rune.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 argv0.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 charstod.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 cistrcmp.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 cistrncmp.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 cistrstr.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 cleanname.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 create.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 dirwstat.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 dofmt.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 dorfmt.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 errfmt.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 exits.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 fmt.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 fmtfd.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 fmtlock.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 fmtprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 fmtquote.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 fmtrune.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 fmtstr.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 fmtvprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 fprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 getfields.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 nulldir.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 pow10.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 print.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 readn.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 rerrstr.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 runeseprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 runesmprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 runesnprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 runevseprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 seek.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 seprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 smprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 snprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 sprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 strdup.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 strecpy.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 sysfatal.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 tokenize.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 u16.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 u32.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 u64.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 utflen.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 utfnlen.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 utfrrune.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 utfrune.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 utfecpy.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 vfprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 vseprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 vsmprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 vsnprint.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 dirstat-posix.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 errstr-posix.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 getuser-posix.c
cc -c -m32  -o getcallerpc-Linux-386.o getcallerpc-Linux-386.S
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 getwd-posix.c
cc -c -m32 -g -O -I/home/pad/kencc/Linux/386/include -I/home/pad/kencc/include -DLINUX_386 sbrk-posix.c
ar ruvs /home/pad/kencc/Linux/386/lib/lib9.a convD2M.o convM2D.o convM2S.o convS2M.o fcallfmt.o qsort.o runestrlen.o strtoll.o rune.o argv0.o charstod.o cistrcmp.o cistrncmp.o cistrstr.o cleanname.o create.o dirwstat.o dofmt.o dorfmt.o errfmt.o exits.o fmt.o fmtfd.o fmtlock.o fmtprint.o fmtquote.o fmtrune.o fmtstr.o fmtvprint.o fprint.o getfields.o nulldir.o pow10.o print.o readn.o rerrstr.o runeseprint.o runesmprint.o runesnprint.o runevseprint.o seek.o seprint.o smprint.o snprint.o sprint.o strdup.o strecpy.o sysfatal.o tokenize.o u16.o u32.o u64.o utflen.o utfnlen.o utfrrune.o utfrune.o utfecpy.o vfprint.o vseprint.o vsmprint.o vsnprint.o dirstat-posix.o errstr-posix.o getuser-posix.o getcallerpc-Linux-386.o getwd-posix.o sbrk-posix.o
